spring:
  rabbitmq:
    host: 10.30.225.112
    port: 5672
    username: test
    password: test
  redis:
    host: 10.30.225.112
    port: 7001
    lettuce:
      pool:
        max-active: 300
    password: 38bddf48f43c48588e0d78761eaa1ce6
  zipkin:
    enabled: true
    sender:
      type: rabbit
  sleuth:
    enabled: true
    http:
      legacy:
        enabled: true
  #jwt密码
  security:
    oauth2:
      jwt:
        signingKey: 123456
  cloud:
    gateway:
       discovery:
           locator:
             enabled: true #开启从注册中心动态创建路由的功能
             lower-case-service-id: true #使用小写服务名，默认是大写
#        routes:
#           - id: requestratelimiter_route
#             uri: http://localhost:8010
#             filters:
#               - name: RequestRateLimiter
#                 args:
#                   redis-rate-limiter.replenishRate: 5 #每秒允许处理的请求数量
#                   redis-rate-limiter.burstCapacity: 5 #每秒最大处理的请求数量
#             predicates:
#               - Method=POST
#           - id: test2
#             uri: http://localhost:8010
#             filters:
#               - name: RequestRateLimiter
#                 args:
#                   redis-rate-limiter.replenishRate: 5 #每秒允许处理的请求数量
#                   redis-rate-limiter.burstCapacity: 5 #每秒最大处理的请求数量
#             predicates:
#               - Method=GET
       default-filters:
          - name: Retry
            args:
               retries: 3
               statuses: BAD_GATEWAY
          - AddResponseHeader=X-Response-Default-Foo, Default-Bar
          - name: RequestRateLimiter
            args:
               redis-rate-limiter.replenishRate: 2  #流速 每秒
               redis-rate-limiter.burstCapacity: 10   #令牌桶的容积
               rate-limiter: "#{@defaultRedisRateLimiter}"  #SPEL表达式去的对应的bean
               key-resolver: "#{@apiKeyResolver}" #SPEL表达式去的对应的bean

feign:
  sentinel:
    enabled: true
  okhttp:
    enabled: true

jetcache:
  statIntervalMinutes: 1
  areaInCacheName: false
  hidePackages: com.springboot.cloud
  local:
    # 默认永久本地缓存
    default:
      type: caffeine
      keyConvertor: fastjson
  remote:
    # 默认永久的远程缓存
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: kryo
      valueDecoder: kryo
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: 10.30.225.112
      port: 7001

#网关白名单，无需要签权url
gate:
  ignore:
    authentication:
      startWith: /oauth,/open,/v2/api-docs

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    com.springboot.cloud: debug
    com.jalja.org.spring: debug
  path: logs/
  file:
    max-size: 1GB